
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 09 20:12:26 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 47;
  public static final int CONST = 22;
  public static final int LPAREN = 8;
  public static final int CONTINUE = 4;
  public static final int ASSIGN_DIV = 40;
  public static final int SEMI_COMMA = 10;
  public static final int FOR = 25;
  public static final int STATIC = 3;
  public static final int RPAREN = 9;
  public static final int AND = 27;
  public static final int LT = 31;
  public static final int OR = 26;
  public static final int BOOL = 48;
  public static final int ASSIGN_MUL = 39;
  public static final int COMMA = 7;
  public static final int CLASS = 20;
  public static final int INC = 23;
  public static final int DIV = 45;
  public static final int ASSIGN_MOD = 41;
  public static final int GEQ = 30;
  public static final int ASSIGN = 36;
  public static final int IF = 18;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int MUL = 44;
  public static final int ASSIGN_PLUS = 37;
  public static final int ADD = 42;
  public static final int NUMBER = 49;
  public static final int MOD = 46;
  public static final int NEQ = 28;
  public static final int IDENT = 50;
  public static final int BREAK = 17;
  public static final int VOID = 13;
  public static final int ASSIGN_MINUS = 38;
  public static final int EQ = 35;
  public static final int LBRACE = 5;
  public static final int ELSE = 19;
  public static final int LSQUARE = 14;
  public static final int READ = 16;
  public static final int RSQUARE = 15;
  public static final int RBRACE = 6;
  public static final int EXTENDS = 21;
  public static final int PROG = 2;
  public static final int LEQ = 32;
  public static final int DEC = 24;
  public static final int GT = 29;
  public static final int SUB = 43;
  public static final int PRINT = 11;
}

