
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 25 14:32:20 CET 2016
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 30;
  public static final int LPAREN = 6;
  public static final int CONTINUE = 26;
  public static final int ASSIGN_DIV = 20;
  public static final int SEMI_COMMA = 5;
  public static final int FOR = 25;
  public static final int STATIC = 12;
  public static final int RPAREN = 7;
  public static final int AND = 47;
  public static final int BGR = 33;
  public static final int OR = 46;
  public static final int COMMA = 8;
  public static final int ASSIGN_MUL = 19;
  public static final int CLASS = 28;
  public static final int INC = 44;
  public static final int ASSIGN_ADD = 17;
  public static final int DIV = 42;
  public static final int ASSIGN_MOD = 21;
  public static final int ASSIGN = 16;
  public static final int IF = 23;
  public static final int DOT = 37;
  public static final int BGE = 34;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int MUL = 41;
  public static final int ADD = 39;
  public static final int MOD = 43;
  public static final int NUMBER = 22;
  public static final int NEQ = 32;
  public static final int IDENT = 48;
  public static final int BREAK = 27;
  public static final int VOID = 11;
  public static final int EQ = 31;
  public static final int BLS = 35;
  public static final int LBRACE = 3;
  public static final int ELSE = 24;
  public static final int LSQUARE = 13;
  public static final int READ = 15;
  public static final int CHARCONST = 49;
  public static final int RSQUARE = 14;
  public static final int ASSIGN_SUB = 18;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 50;
  public static final int EXTENDS = 29;
  public static final int PROG = 2;
  public static final int BLE = 36;
  public static final int DEC = 45;
  public static final int SUB = 40;
  public static final int PRINT = 9;
}

